### ISSUE TITLE
Not working with Hebrew

### ISSUE THREAD

**Issue by miriam18613** [siasio/reverso-context-with-blanks#1]
Hi siasio :)
Awesome idea for an Anki addon! It works great with the original languages specified. I saw that Hebrew was not included there, but once I saw the flag in one of your Github folders, I realized it is supposed to work with Hebrew as well. However when I changed the included languages to include "il" in "Config" in the Anki program, the following happened:

Hebrew shows up as an option in the program, but when I try to get sentences, it autofills with the message seen in the attached screenshot:

![image](https://user-images.githubusercontent.com/101044015/156919749-bd754f2f-22e9-4852-b705-19275f05e843.png)

This happens no matter what word I type in.

Could you please help? Thank you!
Miriam

**Comment by siasio** [comment]
Hello Miriam!
I am very happy to hear that someone likes the add-on's idea!
I have a strong suspicion that the problem here is the alphabet. When I tested it locally, I remember that also Chinese didn't work as expected.
I need to look into my code and, perhaps, add a way to handle various alphabets. I'll inform you as soon as I manage to deal with this issue.
Kind regards,
Siasio

**Comment by siasio** [comment]
Please, reinstall the add-on. In fact, it was a very simple mistake: I used incorrect language codes for a few languages. I hope that now everything works well.
